# Generated by Django 3.1.12 on 2025-10-07 02:05

from django.db import migrations, models
import django.db.models.deletion
import djongo.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20251006_2352'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='user_email',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='user_name',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=djongo.models.TextField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='steps',
            field=djongo.models.TextField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=djongo.models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.user'),
        ),
    ]
