# Generated by Django 3.1.12 on 2025-10-07 02:11

from django.db import migrations, models
import django.db.models.deletion
import djongo.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20251007_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=djongo.models.TextField(default=list),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='steps',
            field=djongo.models.TextField(default=list),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=djongo.models.TextField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.user'),
        ),
    ]
