# Generated by Django 5.2.7 on 2026-01-22 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20251007_0743'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recipe',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
